import { Train, RouteInfo, Station } from '@/types/train';
import { LiveStatus } from '@/types/tracking';
import { WeatherData } from '@/types/weather';
import { JourneyAnalytics } from '@/types/analytics';

export const MOCK_TRAINS: Train[] = [
  {
    id: '12555',
    number: '12555',
    name: 'Gorakhdham SF Express',
    source: { code: 'GKP', name: 'Gorakhpur Junction', city: 'Gorakhpur' },
    destination: { code: 'BTI', name: 'Bathinda Junction', city: 'Bathinda' },
    totalDistanceKm: 1118,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 56,
  },
  {
    id: '12556',
    number: '12556',
    name: 'Gorakhdham SF Express',
    source: { code: 'BTI', name: 'Bathinda Junction', city: 'Bathinda' },
    destination: { code: 'GKP', name: 'Gorakhpur Junction', city: 'Gorakhpur' },
    totalDistanceKm: 1118,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 57,
  },
  {
    id: '12301',
    number: '12301',
    name: 'Howrah - New Delhi Rajdhani Express',
    source: { code: 'HWH', name: 'Howrah Junction', city: 'Kolkata' },
    destination: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    totalDistanceKm: 1451,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A'],
    avgSpeedKmH: 85,
  },
  {
    id: '12302',
    number: '12302',
    name: 'New Delhi - Howrah Rajdhani Express',
    source: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    destination: { code: 'HWH', name: 'Howrah Junction', city: 'Kolkata' },
    totalDistanceKm: 1451,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A'],
    avgSpeedKmH: 85,
  },
  {
    id: '12951',
    number: '12951',
    name: 'Mumbai Tejas Rajdhani Express',
    source: { code: 'MMCT', name: 'Mumbai Central', city: 'Mumbai' },
    destination: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    totalDistanceKm: 1386,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A'],
    avgSpeedKmH: 89,
  },
  {
    id: '12952',
    number: '12952',
    name: 'New Delhi - Mumbai Tejas Rajdhani Express',
    source: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    destination: { code: 'MMCT', name: 'Mumbai Central', city: 'Mumbai' },
    totalDistanceKm: 1386,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A'],
    avgSpeedKmH: 89,
  },
  {
    id: '12002',
    number: '12002',
    name: 'Bhopal Shatabdi Express',
    source: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    destination: { code: 'RKMP', name: 'Rani Kamlapati (Bhopal)', city: 'Bhopal' },
    totalDistanceKm: 708,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['EC', 'CC'],
    avgSpeedKmH: 91,
  },
  {
    id: '12001',
    number: '12001',
    name: 'Rani Kamlapati - New Delhi Shatabdi Express',
    source: { code: 'RKMP', name: 'Rani Kamlapati (Bhopal)', city: 'Bhopal' },
    destination: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    totalDistanceKm: 708,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['EC', 'CC'],
    avgSpeedKmH: 91,
  },
  {
    id: '22436',
    number: '22436',
    name: 'Vande Bharat Express',
    source: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    destination: { code: 'BSB', name: 'Varanasi Junction', city: 'Varanasi' },
    totalDistanceKm: 759,
    runsOn: ['Sun', 'Mon', 'Tue', 'Wed', 'Fri', 'Sat'],
    classes: ['EC', 'CC'],
    avgSpeedKmH: 95,
  },
  {
    id: '22435',
    number: '22435',
    name: 'Varanasi - New Delhi Vande Bharat Express',
    source: { code: 'BSB', name: 'Varanasi Junction', city: 'Varanasi' },
    destination: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    totalDistanceKm: 759,
    runsOn: ['Sun', 'Mon', 'Tue', 'Wed', 'Fri', 'Sat'],
    classes: ['EC', 'CC'],
    avgSpeedKmH: 95,
  },
  {
    id: '15707',
    number: '15707',
    name: 'Amrapali Express',
    source: { code: 'KIR', name: 'Katihar Junction', city: 'Katihar' },
    destination: { code: 'ASR', name: 'Amritsar Junction', city: 'Amritsar' },
    totalDistanceKm: 1572,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['2A', '3A', 'SL'],
    avgSpeedKmH: 52,
  },
  {
    id: '15708',
    number: '15708',
    name: 'Amrapali Express',
    source: { code: 'ASR', name: 'Amritsar Junction', city: 'Amritsar' },
    destination: { code: 'KIR', name: 'Katihar Junction', city: 'Katihar' },
    totalDistanceKm: 1572,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['2A', '3A', 'SL'],
    avgSpeedKmH: 52,
  },
  {
    id: '12626',
    number: '12626',
    name: 'Kerala Express',
    source: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    destination: { code: 'TVC', name: 'Thiruvananthapuram Central', city: 'Trivandrum' },
    totalDistanceKm: 3035,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['2A', '3A', 'SL'],
    avgSpeedKmH: 62,
  },
  {
    id: '12625',
    number: '12625',
    name: 'Kerala Express',
    source: { code: 'TVC', name: 'Thiruvananthapuram Central', city: 'Trivandrum' },
    destination: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    totalDistanceKm: 3035,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['2A', '3A', 'SL'],
    avgSpeedKmH: 62,
  },
  {
    id: '12554',
    number: '12554',
    name: 'Vaishali SF Express',
    source: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    destination: { code: 'SHC', name: 'Saharsa Junction', city: 'Saharsa' },
    totalDistanceKm: 1184,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 61,
  },
  {
    id: '12553',
    number: '12553',
    name: 'Vaishali SF Express',
    source: { code: 'SHC', name: 'Saharsa Junction', city: 'Saharsa' },
    destination: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    totalDistanceKm: 1184,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 61,
  },
  {
    id: '12565',
    number: '12565',
    name: 'Bihar Sampark Kranti Express',
    source: { code: 'DBG', name: 'Darbhanga Junction', city: 'Darbhanga' },
    destination: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    totalDistanceKm: 1164,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 60,
  },
  {
    id: '12566',
    number: '12566',
    name: 'Bihar Sampark Kranti Express',
    source: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    destination: { code: 'DBG', name: 'Darbhanga Junction', city: 'Darbhanga' },
    totalDistanceKm: 1164,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 60,
  },
  {
    id: '12393',
    number: '12393',
    name: 'Sampoorna Kranti Express',
    source: { code: 'PNBE', name: 'Patna Junction', city: 'Patna' },
    destination: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    totalDistanceKm: 1001,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 75,
  },
  {
    id: '12394',
    number: '12394',
    name: 'Sampoorna Kranti Express',
    source: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    destination: { code: 'PNBE', name: 'Patna Junction', city: 'Patna' },
    totalDistanceKm: 1001,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 75,
  },
  {
    id: '12401',
    number: '12401',
    name: 'Nanda Devi AC SF Express',
    source: { code: 'KOTA', name: 'Kota Junction', city: 'Kota' },
    destination: { code: 'DDN', name: 'Dehradun', city: 'Dehradun' },
    totalDistanceKm: 761,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A'],
    avgSpeedKmH: 65,
  },
  {
    id: '12839',
    number: '12839',
    name: 'M.G.R Chennai Central Mail',
    source: { code: 'HWH', name: 'Howrah Junction', city: 'Kolkata' },
    destination: { code: 'MAS', name: 'Chennai Central', city: 'Chennai' },
    totalDistanceKm: 1662,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 60,
  },
  {
    id: '12840',
    number: '12840',
    name: 'Howrah Mail',
    source: { code: 'MAS', name: 'Chennai Central', city: 'Chennai' },
    destination: { code: 'HWH', name: 'Howrah Junction', city: 'Kolkata' },
    totalDistanceKm: 1662,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 60,
  },
  {
    id: '12121',
    number: '12121',
    name: 'Madhya Pradesh Sampark Kranti Express',
    source: { code: 'JBP', name: 'Jabalpur Junction', city: 'Jabalpur' },
    destination: { code: 'NZM', name: 'Hazrat Nizamuddin', city: 'Delhi' },
    totalDistanceKm: 905,
    runsOn: ['Sun', 'Wed', 'Fri'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 65,
  },
  {
    id: '12447',
    number: '12447',
    name: 'Uttar Pradesh Sampark Kranti Express',
    source: { code: 'MKP', name: 'Manikpur Junction', city: 'Manikpur' },
    destination: { code: 'NZM', name: 'Hazrat Nizamuddin', city: 'Delhi' },
    totalDistanceKm: 694,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['2A', '3A', 'SL'],
    avgSpeedKmH: 62,
  },
  {
    id: '12217',
    number: '12217',
    name: 'Kerala Sampark Kranti Express',
    source: { code: 'KCVL', name: 'Kochuveli', city: 'Trivandrum' },
    destination: { code: 'CDG', name: 'Chandigarh Junction', city: 'Chandigarh' },
    totalDistanceKm: 3095,
    runsOn: ['Sat', 'Mon'],
    classes: ['2A', '3A', 'SL'],
    avgSpeedKmH: 59,
  },
  {
    id: '12907',
    number: '12907',
    name: 'Maharashtra Sampark Kranti Express',
    source: { code: 'BDTS', name: 'Bandra Terminus', city: 'Mumbai' },
    destination: { code: 'NZM', name: 'Hazrat Nizamuddin', city: 'Delhi' },
    totalDistanceKm: 1367,
    runsOn: ['Wed', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 80,
  },
  {
    id: '12925',
    number: '12925',
    name: 'Paschim SF Express',
    source: { code: 'MMCT', name: 'Mumbai Central', city: 'Mumbai' },
    destination: { code: 'KLK', name: 'Kalka', city: 'Kalka' },
    totalDistanceKm: 1673,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 58,
  },
  {
    id: '12801',
    number: '12801',
    name: 'Purushottam SF Express',
    source: { code: 'PURI', name: 'Puri', city: 'Puri' },
    destination: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    totalDistanceKm: 1862,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 61,
  },
  {
    id: '12391',
    number: '12391',
    name: 'Shramjeevi SF Express',
    source: { code: 'RGD', name: 'Rajgir', city: 'Rajgir' },
    destination: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    totalDistanceKm: 1002,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 58,
  },
  {
    id: '12137',
    number: '12137',
    name: 'Punjab Mail',
    source: { code: 'CSMT', name: 'Mumbai CSMT', city: 'Mumbai' },
    destination: { code: 'FZR', name: 'Firozpur Cantt', city: 'Firozpur' },
    totalDistanceKm: 1928,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 57,
  },
  {
    id: '12417',
    number: '12417',
    name: 'Prayagraj SF Express',
    source: { code: 'PRYJ', name: 'Prayagraj Junction', city: 'Prayagraj' },
    destination: { code: 'NDLS', name: 'New Delhi', city: 'Delhi' },
    totalDistanceKm: 635,
    runsOn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    classes: ['1A', '2A', '3A', 'SL'],
    avgSpeedKmH: 67,
  },
];

export const MOCK_STATIONS_12301: Station[] = [
  { code: 'HWH', name: 'Howrah Junction', arrivalTime: '16:50', departureTime: '16:50', distanceKm: 0, day: 1, platform: '9', lat: 22.5839, lon: 88.3428, elevationM: 9, passed: true, actualArrival: '16:50', actualDeparture: '16:50', delayMinutes: 0 },
  { code: 'ASN', name: 'Asansol Junction', arrivalTime: '18:57', departureTime: '19:00', distanceKm: 200, day: 1, platform: '5', lat: 23.6833, lon: 86.9833, elevationM: 126, passed: true, actualArrival: '18:59', actualDeparture: '19:02', delayMinutes: 2 },
  { code: 'DHN', name: 'Dhanbad Junction', arrivalTime: '19:55', departureTime: '20:00', distanceKm: 259, day: 1, platform: '3', lat: 23.7957, lon: 86.4304, elevationM: 232, passed: true, actualArrival: '20:05', actualDeparture: '20:10', delayMinutes: 10 },
  { code: 'GAYA', name: 'Gaya Junction', arrivalTime: '22:31', departureTime: '22:34', distanceKm: 459, day: 1, platform: '1', lat: 24.8000, lon: 85.0000, elevationM: 113, passed: true, actualArrival: '22:45', actualDeparture: '22:48', delayMinutes: 14 },
  { code: 'DDU', name: 'Pt. DD Upadhyaya Jn', arrivalTime: '00:45', departureTime: '00:55', distanceKm: 664, day: 2, platform: '7', lat: 25.2819, lon: 83.1189, elevationM: 78, passed: true, actualArrival: '00:57', actualDeparture: '01:07', delayMinutes: 12 },
  { code: 'PRYJ', name: 'Prayagraj Junction', arrivalTime: '02:43', departureTime: '02:45', distanceKm: 817, day: 2, platform: '1', lat: 25.4484, lon: 81.8324, elevationM: 98, passed: false, actualArrival: '02:55', actualDeparture: '02:57', delayMinutes: 12 },
  { code: 'CNB', name: 'Kanpur Central', arrivalTime: '04:50', departureTime: '04:55', distanceKm: 1011, day: 2, platform: '1', lat: 26.4542, lon: 80.3500, elevationM: 126, passed: false, delayMinutes: 8 },
  { code: 'NDLS', name: 'New Delhi', arrivalTime: '10:05', departureTime: '10:05', distanceKm: 1451, day: 2, platform: '16', lat: 28.6429, lon: 77.2195, elevationM: 216, passed: false, delayMinutes: 5 },
];

export const MOCK_POLYLINE_12301: [number, number][] = [
  [88.3428, 22.5839],
  [87.8500, 22.9000],
  [86.9833, 23.6833],
  [86.4304, 23.7957],
  [85.6000, 24.2000],
  [85.0000, 24.8000],
  [84.0000, 25.0000],
  [83.1189, 25.2819],
  [82.3000, 25.3500],
  [81.8324, 25.4484],
  [81.0000, 25.9000],
  [80.3500, 26.4542],
  [79.0000, 27.2000],
  [78.0000, 27.8000],
  [77.2195, 28.6429],
];

export const MOCK_LIVE_STATUS: Record<string, LiveStatus> = {
  '12301': {
    trainNumber: '12301',
    trainName: 'Howrah Rajdhani Express',
    currentStation: {
      code: 'DDU',
      name: 'Pt. DD Upadhyaya Junction',
      actualDeparture: '01:07 AM',
      delayMinutes: 12,
    },
    nextStation: {
      code: 'PRYJ',
      name: 'Prayagraj Junction',
      eta: '02:55 AM',
      scheduledArrival: '02:43 AM',
      distanceRemainingKm: 64,
    },
    coordinates: [82.5500, 25.3200], // Currently between DDU and PRYJ
    heading: 285,
    speedKmH: 112,
    delayMinutes: 12,
    statusText: 'Running 12 mins late • Next: Prayagraj Jn (64 km)',
    progressPercentage: 52,
    lastUpdated: new Date().toISOString(),
    isStarted: true,
    isCompleted: false,
  },
  '12951': {
    trainNumber: '12951',
    trainName: 'Mumbai Tejas Rajdhani Express',
    currentStation: {
      code: 'RTM',
      name: 'Ratlam Junction',
      actualDeparture: '22:40 PM',
      delayMinutes: 0,
    },
    nextStation: {
      code: 'KOTA',
      name: 'Kota Junction',
      eta: '01:15 AM',
      scheduledArrival: '01:15 AM',
      distanceRemainingKm: 120,
    },
    coordinates: [75.4000, 24.2000],
    heading: 15,
    speedKmH: 128,
    delayMinutes: 0,
    statusText: 'On Time • Speed 128 km/h • Next: Kota Jn',
    progressPercentage: 48,
    lastUpdated: new Date().toISOString(),
    isStarted: true,
    isCompleted: false,
  },
  '12002': {
    trainNumber: '12002',
    trainName: 'Bhopal Shatabdi Express',
    currentStation: {
      code: 'AGC',
      name: 'Agra Cantt',
      actualDeparture: '07:55 AM',
      delayMinutes: 3,
    },
    nextStation: {
      code: 'GWL',
      name: 'Gwalior Junction',
      eta: '09:20 AM',
      scheduledArrival: '09:17 AM',
      distanceRemainingKm: 42,
    },
    coordinates: [78.1000, 26.8000],
    heading: 170,
    speedKmH: 140,
    delayMinutes: 3,
    statusText: 'Running 3 mins late • Cruising at 140 km/h',
    progressPercentage: 35,
    lastUpdated: new Date().toISOString(),
    isStarted: true,
    isCompleted: false,
  },
};

export const MOCK_WEATHER: Record<string, WeatherData> = {
  current: {
    tempC: 29,
    condition: 'Partly Cloudy',
    icon: '02d',
    humidity: 68,
    windKmH: 14,
    rainProbPercentage: 20,
    locationName: 'Near Mirzapur, UP',
    feelsLikeC: 31,
  },
  destination: {
    tempC: 34,
    condition: 'Clear Sky',
    icon: '01d',
    humidity: 45,
    windKmH: 18,
    rainProbPercentage: 5,
    locationName: 'New Delhi',
    feelsLikeC: 36,
  },
};

export const MOCK_ANALYTICS_12301: JourneyAnalytics = {
  completionPercentage: 52,
  distanceCoveredKm: 753,
  remainingDistanceKm: 698,
  totalDistanceKm: 1451,
  highestElevationM: 232,
  highestElevationLocation: 'Dhanbad Plateau (232m)',
  avgSpeedKmH: 88,
  maxSpeedKmH: 130,
  delayTrend: [
    { stationCode: 'HWH', stationName: 'Howrah Jn', delayMinutes: 0, scheduledTime: '16:50', actualTime: '16:50', distanceKm: 0 },
    { stationCode: 'ASN', stationName: 'Asansol Jn', delayMinutes: 2, scheduledTime: '18:57', actualTime: '18:59', distanceKm: 200 },
    { stationCode: 'DHN', stationName: 'Dhanbad Jn', delayMinutes: 10, scheduledTime: '19:55', actualTime: '20:05', distanceKm: 259 },
    { stationCode: 'GAYA', stationName: 'Gaya Jn', delayMinutes: 14, scheduledTime: '22:31', actualTime: '22:45', distanceKm: 459 },
    { stationCode: 'DDU', stationName: 'Pt. DD Upadhyaya', delayMinutes: 12, scheduledTime: '00:45', actualTime: '00:57', distanceKm: 664 },
    { stationCode: 'PRYJ', stationName: 'Prayagraj Jn', delayMinutes: 12, scheduledTime: '02:43', actualTime: '02:55', distanceKm: 817 },
    { stationCode: 'CNB', stationName: 'Kanpur Central', delayMinutes: 8, scheduledTime: '04:50', actualTime: '04:58', distanceKm: 1011 },
    { stationCode: 'NDLS', stationName: 'New Delhi', delayMinutes: 5, scheduledTime: '10:05', actualTime: '10:10', distanceKm: 1451 },
  ],
  elevationProfile: [
    { distanceKm: 0, elevationM: 9, stationName: 'Howrah', isStation: true },
    { distanceKm: 100, elevationM: 45 },
    { distanceKm: 200, elevationM: 126, stationName: 'Asansol', isStation: true },
    { distanceKm: 259, elevationM: 232, stationName: 'Dhanbad', isStation: true },
    { distanceKm: 350, elevationM: 180 },
    { distanceKm: 459, elevationM: 113, stationName: 'Gaya', isStation: true },
    { distanceKm: 550, elevationM: 95 },
    { distanceKm: 664, elevationM: 78, stationName: 'DDU', isStation: true },
    { distanceKm: 817, elevationM: 98, stationName: 'Prayagraj', isStation: true },
    { distanceKm: 1011, elevationM: 126, stationName: 'Kanpur', isStation: true },
    { distanceKm: 1200, elevationM: 165 },
    { distanceKm: 1451, elevationM: 216, stationName: 'New Delhi', isStation: true },
  ],
  landmarks: [
    { id: '1', name: 'Hooghly River Bridge', type: 'bridge', coordinates: [88.345, 22.588], distanceFromRouteKm: 0.1, description: 'Historic railway bridge exiting Kolkata.' },
    { id: '2', name: 'Parasnath Hill Peak', type: 'mountain', coordinates: [86.150, 23.960], distanceFromRouteKm: 12, description: 'Highest mountain peak in Jharkhand (1365m).' },
    { id: '3', name: 'Ganges River Crossing (DDU)', type: 'river', coordinates: [83.050, 25.260], distanceFromRouteKm: 0.2, description: 'Majestic bridge across the Sacred Ganges.' },
    { id: '4', name: 'Triveni Sangam Prayagraj', type: 'tourist', coordinates: [81.880, 25.430], distanceFromRouteKm: 4.5, description: 'Confluence of Ganga, Yamuna, and Saraswati rivers.' },
  ],
};
